#!/bin/sh

ABSPATH=$(git rev-parse --show-toplevel)
cd $ABSPATH

SCRIPT_NAME=$(ls scripts/ | grep "$1.sh" | head -1)

if [ "$SCRIPT_NAME" != "$1.sh" ]; then
	echo "Command not found"
	exit
fi

scripts/./$SCRIPT_NAME $2 $3